name: FirstCI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint HTML
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTML linter
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Lint index.html
        run: tidy -errors index.html || true


  build:
    name: Build Docker Image
    runs-on: ubuntu
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t html-app:ci .


  run:
    name: Run Container on Port 8585
    runs-on: ubuntu
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          docker run -d \
            -p 8585:8080 \
            --name html-test \
            html-app:ci

            
  test:
    name: test Container on Port 8585
    runs-on: ubuntu
    needs: run

    steps:
      - name: Verify application
        run: curl -I http://localhost:8585

      - name: Show container logs (debug)
        run: docker logs html-test
